spring:
  application:
    name: ribbon
server:
  port: 7071
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
